In [1]:
import os
import git_ck 
import repo_utils as ru
import pandas as pd

In [2]:
   
try:
    ru.check_repo()
    ru.check_folder()
except:
    print("Warning")

In [3]:
measures = ["cbo", "wmc", "dit", "noc"]

In [4]:
cmr = git_ck.commit_measure_release(measures)

In [5]:
cmr

,Tag,Commit Hash,Commit Date,cbo,wmc,dit,noc
0,v1.0,7262545c53e58195fb58696d0e8cc5835517f527class.csv,2014-05-19T08:06:24+02:00,10.130435,7.065217,1.565217,0.0
1,v1.1,46e7bd4a544c66aa8a2d2a85719f38920123b3d5class.csv,2014-07-30T22:24:59+02:00,8.608696,7.217391,1.565217,0.0
2,v1.2.1,a0291e2fbec8b89f35bd61c1e4c68fe85e527f93class.csv,2016-01-23T14:11:23+01:00,9.416667,7.520833,1.583333,0.0
3,v1.3,c7f9084a61264f463b67f2f920a90ddb324c04f2class.csv,2016-01-28T05:40:05+01:00,9.416667,7.520833,1.583333,0.0
4,v1.4,2625673fe6bdcdfdbec951af8f20809eec49f092class.csv,2016-04-27T21:36:27+02:00,9.437500,7.833333,1.583333,0.0
5,v1.5,6c7748eebd5fba4bdc83a4497b546aacfe20e45eclass.csv,2016-10-15T23:43:55+02:00,9.039216,7.725490,1.607843,0.0
6,v1.6,5c891585d2eb8ac91cf885032f95c51f6b2a734aclass.csv,2017-11-05T12:14:00+01:00,4.200000,45.600000,2.200000,0.0
7,v1.7,7c665511b37897961a2e693ba80a2a9ebf1b6ee8class.csv,2018-07-05T06:01:29+02:00,5.000000,44.714286,2.000000,0.0
8,v1.8,4bddc1e203e3785f4a6046625abe355a8676da9bclass.csv,2019-02-07T22:19:32+01:00,5.000000,44.857143,2.000000,0.0
9,v2.0,7ddfddacc817f3d0cf813f4e39e4397a2896cc72class.csv,2020-02-27T15:41:39+01:00,5.000000,44.857143,2.000000,0.0
10,v2.1,677aa5b5dbc9f2f0cd89518ba8d16725dd7703a0class.csv,2020-10-03T10:50:55+02:00,5.000000,44.857143,2.000000,0.0
11,v2.1.1,d56bb32f4ad833cda0acc2c63cb72ea151257d24class.csv,2021-05-24T08:06:38+02:00,5.000000,46.285714,2.000000,0.0
12,v2.1.2,ba8e26ece080b799e5a6ec66a9ae88216eae90acclass.csv,2021-08-05T13:30:47+02:00,5.142857,48.000000,2.000000,0.0
13,v2.1.3,e6eca6ea36a8e008f12b480413eb1311733fca56class.csv,2022-01-23T07:48:37+01:00,5.142857,47.714286,2.000000,0.0
14,v2.1.4,c2b4bffcd39fb08c1dad0f56f3cfaed29eabaf1eclass.csv,2023-02-12T09:04:53+01:00,4.555556,42.111111,1.777778,0.0

In [2]:
lista, folder= ru.inizia_analisi("v2.0")

In [4]:
lista, folder

(                                 Commit Hash            Data del Commit
 0   117c84823b376902cf208c2babf1dc7f4142c912  2014-05-06 07:06:34-07:00
 1   3f5e8ec805934ca9b0db905d093ef9949bbaf3fb  2014-05-19 08:02:02+02:00
 2   7262545c53e58195fb58696d0e8cc5835517f527  2014-05-19 08:06:24+02:00
 3   43f7cfecbd273c5cac4a7c3083db5b31cb67921e  2014-07-04 09:20:53+02:00
 4   618d7f4ddf0f8e3dec259cc0d0ee2e588bf4ab65  2014-07-04 09:22:30+02:00
 5   3e3d55f9fffb4c22c64a1e93c7e334fb9e2b1d9d  2014-07-19 20:21:13+02:00
 6   c9dd0667e398d77652ffaf3ff03f46ada4019fc0  2014-07-19 21:53:27+02:00
 7   5279dddcdf9ebfd5a4f4b7d5a5d595dcc86abe37  2014-07-19 21:56:28+02:00
 8   c705eae618faa0a1ef9690a258591e6017bd9cce  2014-07-19 22:16:26+02:00
 9   543fee39bfbc24d5714a2a29c673efa8b5feecba  2014-07-22 11:32:47+02:00
 10  65714a05c0b77db4d43fe2f290a1c46a2f3cee75  2014-07-22 11:57:57+02:00
 11  724e2d9c82fc25ed2491b4734b90f9d557ca3dbe  2014-07-22 14:43:12+02:00
 12  aedb14e73f1ff786f3a05b7f99c37b53cd5d882f  2014-07-25 12:31:50+02:00
 13  52667655b4b55a632d52830af9250e2d3e734f6d  2014-07-25 14:08:22+02:00
 14  8aa78ef6b718ed157c0557bdb238338a47305da7  2014-07-25 14:11:34+02:00
 15  73fdb5c54e15ecc95e1cb18a43a262db3579b5d3  2014-07-30 17:31:45+02:00
 16  eec66bd4ff54b82a66feee37a3891643bcb897a0  2014-07-30 17:35:56+02:00
 17  b5fede71c7b54035bf383a6e0db2833df3f6818a  2014-07-30 17:40:44+02:00
 18  c9c845fc3c7cf438c2799da2b295f1dffadd0d14  2014-07-30 17:46:38+02:00
 19  784c534e5162772a3f1e0d0fb19c7c424e8e4463  2014-07-30 21:59:39+02:00
 20  46e7bd4a544c66aa8a2d2a85719f38920123b3d5  2014-07-30 22:24:59+02:00
 21  d4826af33fc989487512f5ab9da35ed4df849b17  2014-08-03 13:35:48-04:00
 22  738ff24c82458691acf14af76ecfdec26b0a7279  2014-08-03 20:43:21+02:00
 23  95bcde7b2ce4d8d203b220c094bd07bc0fa8bfba  2014-08-31 15:51:11+02:00
 24  ccf76c8a61e4b35b3ae18b932deb847cc485846d  2014-08-31 15:55:26+02:00
 25  995c36a0ba74e386ba335d9c97bfd75010c40e67  2014-08-31 16:03:14+02:00
 26  8159cc19edf48979d3ca723d19a1bffa56376515  2014-11-09 11:48:18+01:00
 27  ad0e85eab51962be2251ef2244cf42160e777ab0  2014-11-11 22:33:25+01:00
 28  22784aff68c9d3355dc8bd9280664bc3b05a22da  2015-01-08 18:52:03+01:00
 29  ab32c7d61c9c18fb1b8572619683c35d9887b33f  2015-01-08 19:30:40+01:00,
 'fxgraphics2d')

In [4]:
lf = git_ck.commit_measure_interval(measures, lista, 20, folder )

c:\Users\simon\Documents\GitHub\ing-soft2\git_ck.py:148: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  commit['Commit Hash'] = commit['Commit Hash'] + 'class.csv'

In [5]:
lf

,Commit Hash,Data del Commit,cbo,wmc,dit,noc
0,46e7bd4a544c66aa8a2d2a85719f38920123b3d5class.csv,2014-07-30 22:24:59+02:00,8.608696,7.217391,1.565217,0.0
1,d4826af33fc989487512f5ab9da35ed4df849b17class.csv,2014-08-03 13:35:48-04:00,8.608696,7.239130,1.565217,0.0
2,738ff24c82458691acf14af76ecfdec26b0a7279class.csv,2014-08-03 20:43:21+02:00,8.608696,7.239130,1.565217,0.0
3,95bcde7b2ce4d8d203b220c094bd07bc0fa8bfbaclass.csv,2014-08-31 15:51:11+02:00,8.608696,7.239130,1.565217,0.0
4,ccf76c8a61e4b35b3ae18b932deb847cc485846dclass.csv,2014-08-31 15:55:26+02:00,8.608696,7.239130,1.565217,0.0
5,995c36a0ba74e386ba335d9c97bfd75010c40e67class.csv,2014-08-31 16:03:14+02:00,8.608696,7.239130,1.565217,0.0
6,8159cc19edf48979d3ca723d19a1bffa56376515class.csv,2014-11-09 11:48:18+01:00,8.608696,7.239130,1.565217,0.0
7,ad0e85eab51962be2251ef2244cf42160e777ab0class.csv,2014-11-11 22:33:25+01:00,8.608696,7.456522,1.565217,0.0
8,22784aff68c9d3355dc8bd9280664bc3b05a22daclass.csv,2015-01-08 18:52:03+01:00,8.333333,7.479167,1.583333,0.0
9,ab32c7d61c9c18fb1b8572619683c35d9887b33fclass.csv,2015-01-08 19:30:40+01:00,8.333333,7.479167,1.583333,0.0

In [5]:
listamezza = ru.sfoglia_commit(lista, 150)
listamezza

                            Titolo del Commit            Data del Commit
150  cf00649b16baf32fa4fa4bf872ec02def219f83e  2018-07-05 05:59:16+02:00
151  4cd172f2b7fd9d74f2bebd7802d65c9d7e5fc224  2018-07-05 06:00:24+02:00
152  7c665511b37897961a2e693ba80a2a9ebf1b6ee8  2018-07-05 06:01:29+02:00
153  0f4077a6c4503e71c44557c6c10e920b2bb7b1cd  2018-07-05 06:36:43+02:00
154  03c9ef2c8f0db842dce521d5a688fe12faaccbd4  2019-01-30 23:10:10+01:00
155  11f57d5f20fe0b6dd8a9d944c21e298d85cf8db4  2019-01-30 23:14:35+01:00
156  eb1f6586bb1bd2117841e3c810073fff4f6afd12  2019-01-30 23:23:24+01:00
157  75a73bd87c6cf5364a3067b579eae9636e40199d  2019-01-30 23:25:32+01:00
158  4bddc1e203e3785f4a6046625abe355a8676da9b  2019-02-07 22:19:32+01:00
159  be47c725f86d7a339770113c685b136b3eb892c8  2020-02-25 18:05:02+01:00

In [3]:
pd=ru.dataCommit()
pd.to_csv("C:\\Users\\simon\\Desktop\\dati importanti\\committo.csv")

In [8]:
commit_hash = '3baf3aa00008701df7fb8b8440a910fdb654a304'
git_ck.ck_metrics_for_single_commit(commit_hash)
result_df= pd.read_csv(os.path.abspath('output\\3baf3aa00008701df7fb8b8440a910fdb654a304class.csv'))

In [10]:
result_df

,file,class,type,cbo,cboModified,fanin,fanout,wmc,dit,noc,...,assignmentsQty,mathOperationsQty,variablesQty,maxNestedBlocksQty,anonymousClassesQty,innerClassesQty,lambdasQty,uniqueWordsQty,modifiers,logStatementsQty
0,c:\Users\simon\Documents\GitHub\ing-soft2\Repo...,org.jfree.fx.FXGraphics2D,class,17,18,1,17,208,3,0,...,161,18,133,3,0,0,0,576,1,0
1,c:\Users\simon\Documents\GitHub\ing-soft2\Repo...,org.jfree.fx.FXGraphicsDevice,class,1,3,2,1,5,2,0,...,2,0,2,0,0,0,0,30,1,0
2,c:\Users\simon\Documents\GitHub\ing-soft2\Repo...,org.jfree.fx.FXGraphicsConfiguration,class,2,4,2,2,10,2,0,...,3,0,3,1,0,0,0,42,1,0
3,c:\Users\simon\Documents\GitHub\ing-soft2\Repo...,org.jfree.fx.FXHints,class,1,1,0,1,1,2,0,...,1,0,1,0,0,1,0,77,17,0
4,c:\Users\simon\Documents\GitHub\ing-soft2\Repo...,org.jfree.fx.FXHints$Key,innerclass,0,0,0,0,4,2,0,...,0,0,0,1,0,0,0,32,9,0

In [5]:
measures = ["cbo", "wmc", "dit", "noc"]
git_ck.commit_measure(measures ,commit_hash)

                                  class  cbo  wmc  dit  noc
0             org.jfree.fx.FXGraphics2D   17  208    3    0
1         org.jfree.fx.FXGraphicsDevice    1    5    2    0
2  org.jfree.fx.FXGraphicsConfiguration    2   10    2    0
3                  org.jfree.fx.FXHints    1    1    2    0
4              org.jfree.fx.FXHints$Key    0    4    2    0

In [9]:
git_ck.commit_measure_avg("wmc" ,commit_hash+"class.csv")

45.6

In [3]:
metrics = ["wmc", "dit", "noc", "cbo"]
ff = git_ck.commit_measure_year(2014, metrics)

In [4]:
ff

,name,wmc,dit,noc,cbo
0,117c84823b376902cf208c2babf1dc7f4142c912class.csv,NaN,NaN,NaN,NaN
1,3e3d55f9fffb4c22c64a1e93c7e334fb9e2b1d9dclass.csv,7.130435,1.565217,0.0,10.130435
2,3f5e8ec805934ca9b0db905d093ef9949bbaf3fbclass.csv,7.065217,1.565217,0.0,10.130435
3,43f7cfecbd273c5cac4a7c3083db5b31cb67921eclass.csv,7.130435,1.565217,0.0,10.130435
4,46e7bd4a544c66aa8a2d2a85719f38920123b3d5class.csv,7.217391,1.565217,0.0,8.608696
5,52667655b4b55a632d52830af9250e2d3e734f6dclass.csv,7.217391,1.565217,0.0,10.130435
6,5279dddcdf9ebfd5a4f4b7d5a5d595dcc86abe37class.csv,7.130435,1.565217,0.0,10.130435
7,543fee39bfbc24d5714a2a29c673efa8b5feecbaclass.csv,7.152174,1.565217,0.0,10.130435
8,618d7f4ddf0f8e3dec259cc0d0ee2e588bf4ab65class.csv,7.130435,1.565217,0.0,10.130435
9,65714a05c0b77db4d43fe2f290a1c46a2f3cee75class.csv,7.173913,1.565217,0.0,10.130435
10,724e2d9c82fc25ed2491b4734b90f9d557ca3dbeclass.csv,7.217391,1.565217,0.0,10.130435
11,7262545c53e58195fb58696d0e8cc5835517f527class.csv,7.065217,1.565217,0.0,10.130435
12,738ff24c82458691acf14af76ecfdec26b0a7279class.csv,7.239130,1.565217,0.0,8.608696
13,73fdb5c54e15ecc95e1cb18a43a262db3579b5d3class.csv,7.217391,1.565217,0.0,10.130435
14,784c534e5162772a3f1e0d0fb19c7c424e8e4463class.csv,7.217391,1.565217,0.0,8.608696
15,8159cc19edf48979d3ca723d19a1bffa56376515class.csv,7.239130,1.565217,0.0,8.608696
16,8aa78ef6b718ed157c0557bdb238338a47305da7class.csv,7.217391,1.565217,0.0,10.130435
17,95bcde7b2ce4d8d203b220c094bd07bc0fa8bfbaclass.csv,7.239130,1.565217,0.0,8.608696
18,995c36a0ba74e386ba335d9c97bfd75010c40e67class.csv,7.239130,1.565217,0.0,8.608696
19,ad0e85eab51962be2251ef2244cf42160e777ab0class.csv,7.456522,1.565217,0.0,8.608696
20,aedb14e73f1ff786f3a05b7f99c37b53cd5d882fclass.csv,7.217391,1.565217,0.0,10.130435
21,b5fede71c7b54035bf383a6e0db2833df3f6818aclass.csv,7.217391,1.565217,0.0,10.130435
22,c705eae618faa0a1ef9690a258591e6017bd9cceclass.csv,7.130435,1.565217,0.0,10.130435
23,c9c845fc3c7cf438c2799da2b295f1dffadd0d14class.csv,7.217391,1.565217,0.0,10.130435
24,c9dd0667e398d77652ffaf3ff03f46ada4019fc0class.csv,7.130435,1.565217,0.0,10.130435
25,ccf76c8a61e4b35b3ae18b932deb847cc485846dclass.csv,7.239130,1.565217,0.0,8.608696
26,d4826af33fc989487512f5ab9da35ed4df849b17class.csv,7.239130,1.565217,0.0,8.608696
27,eec66bd4ff54b82a66feee37a3891643bcb897a0class.csv,7.217391,1.565217,0.0,10.130435